import type { Metadata } from "next";
import { Luckiest_Guy, Onest } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const luckiestGuy = Luckiest_Guy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-luckiest-guy",
  display: "swap",
});

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
});

const anakPaud = localFont({
  src: "./fonts/anak-paud.ttf",
  variable: "--font-anak-paud",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${luckiestGuy.variable} ${onest.variable} ${anakPaud.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
